package cvmcode

const (
		OK = 0
		PARAM_ERR = 1
		PREPARE_POST_DATA_FAIL = 2
		NEWREQUEST_FAIL = 3
		DO_REQUEST_FAIL = 4
		READ_RESPONSE_FAIL = 5
		PARSE_CGW_RESPONSE__FAIL = 6
		CGW_NO_RETURNCODE = 7
		CGW_NO_RETURNMSG = 8
		CGW_TIMEOUT = 9
		CGW_HTTP_RETRUNCODE_NOT_200 = 10
		CGW_INTERFACE_ALL_FAIL = 11
)
